# Site settings
title: Andy Whale
email: andy@awhale.co.uk
description: "Programming, Photography, Natural History, Electric Guitar, Tech, Etc"
baseurl: ""
url: "http://awhale.co.uk"
twitter_username: andywhalephoto
github_username:  andywhale
facebook_username: andywhalephoto
paginate: 5

# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-cayman
